# -*- coding: utf-8 -*-
"""Visualize Distributions With Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ic1y5Xmk2OYQd3_A6kIIG54T-e34t8Jp
"""



"""Seaborn is a library that uses Matplotlib underneath to plot graphs. It will be used to visualize random distributions.


"""

#Seaborn is a library that uses Matplotlib underneath to plot graphs. It will be used to visualize random distributions.
!pip install seaborn
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns



sns.distplot([0, 1, 2, 3, 4, 5])


#sns.distplot([0, 1, 2, 3, 4, 5], hist=False) #for without histogram

plt.show()